import type { I18n } from "./index.js";

export const enI18n: I18n = {
  // HTML Security Report
  securityReportTitle: "AWS Security Scan Report",
  securityScore: "Security Score",
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
  scanStatistics: "Scan Statistics",
  module: "Module",
  resources: "Resources",
  findings: "Findings",
  status: "Status",
  allFindings: "All Findings",
  recommendations: "Recommendations",
  unique: "unique",
  showMore: "Show more",
  noIssuesFound: "No security issues found.",
  allModulesClean: "All modules clean",
  generatedBy: "Generated by AWS Security MCP Server",
  informationalOnly: "This report is for informational purposes only.",

  // MLPS Report
  mlpsTitle: "MLPS Level 3 Pre-Check Report",
  mlpsDisclaimer:
    "This report is for MLPS Level 3 pre-check reference, providing cloud platform configuration check data and recommendations. Compliance determination (compliant/partially compliant/non-compliant) must be confirmed by a certified assessment institution. (GB/T 22239-2019 full checklist: 184 items)",
  checkedItems: "Checked Items",
  noIssues: "No Issues Found",
  issuesFound: "Issues Found",
  notChecked: "Not Checked",
  cloudProvider: "Cloud Provider Responsible",
  manualReview: "Manual Review Required",
  notApplicable: "Not Applicable",
  checkResult: "Check Result",
  noRelatedIssues: "Check Result: No related issues found",
  issuesFoundCount: (n: number) =>
    `Check Result: Found ${n} related issue${n === 1 ? "" : "s"}`,
  remediation: "Remediation",
  remediationItems: (n: number) =>
    `Remediation Items (${n} unique)`,
  showRemaining: (n: number) => `Show remaining ${n} items`,

  // HW Defense Checklist
  hwChecklistTitle:
    "\ud83d\udccb Cyber Defense Drill Supplementary Reminders (Beyond Automated Scanning)",
  hwChecklistSubtitle:
    "The following items require manual verification and execution:",
  hwEmergencyIsolation: `\u26a0\ufe0f Emergency Isolation / Incident Response Plan
  \u25a1 Prepare dedicated isolation security groups (no Inbound/Outbound rules)
  \u25a1 Establish instance isolation SOP: Alert \u2192 Investigate \u2192 Block attacker IP \u2192 Network isolation \u2192 Security response \u2192 Log attack details
  \u25a1 Define emergency response procedures for each system (production core/non-core/test/dev)
  \u25a1 Identify responsible personnel and contacts for each project account and resource`,
  hwTestEnvShutdown: `\u26a0\ufe0f Test/Development Environment Handling
  \u25a1 Shut down non-critical systems during the drill period
  \u25a1 Shut down test/dev environments or maintain same security baseline as production
  \u25a1 Confirm which environments can be emergency-stopped to prevent attack propagation`,
  hwDutyTeam: `\u26a0\ufe0f On-Duty Team Formation
  \u25a1 7\u00d724 monitoring and rapid response team
  \u25a1 Technical and risk analysis team
  \u25a1 Security policy deployment team
  \u25a1 Business response team
  \u25a1 Confirm AWS TAM/Support contact information (ES/EOP customers)`,
  hwNetworkDiagram: `\u26a0\ufe0f Ingress/Egress Path Architecture Diagram
  \u25a1 Ensure all Internet/DX dedicated line ingress/egress paths are clearly marked in architecture diagrams
  \u25a1 Clarify data flow for each ELB/Public EC2/S3/DX
  \u25a1 Identify all internet-facing data interaction interfaces`,
  hwPentest: `\u26a0\ufe0f Proactive Penetration Testing
  \u25a1 Contact security vendors for simulated attack drills before the exercise
  \u25a1 Conduct security hardening based on penetration test reports
  \u25a1 Monitor AWS security advisories (known vulnerabilities and patches)`,
  hwWarRoom: `\u26a0\ufe0f WAR-ROOM Real-Time Communication
  \u25a1 Create dedicated communication channels for the drill period (Teams/Slack/Chime)
  \u25a1 Establish WAR-ROOM connection with AWS TAM (Enterprise Support customers)
  \u25a1 Standardize case title format: "[CyberDrill] + Issue Description"`,
  hwCredentials: `\u26a0\ufe0f Password & Credential Management
  \u25a1 All IAM users must have MFA enabled
  \u25a1 Access key rotation cycle \u2264 90 days
  \u25a1 Avoid shared account usage
  \u25a1 No plaintext passwords in S3/Lambda/application code`,
  hwPostOptimization: `\u26a0\ufe0f Post-Drill Optimization
  \u25a1 Address and remediate each item from the attack report
  \u25a1 Establish periodic security maintenance processes with the security team
  \u25a1 Continuously fill security risk gaps`,
  hwReference:
    "Reference: AWS Cyber Defense Drill Standard Operation Procedure (Compliance IEM)",

  // Service Reminders
  serviceReminderTitle:
    "\u26a1 The following security services are not enabled; some checks cannot be performed:",
  serviceReminderFooter:
    "Re-scan after enabling the above services for a more complete security assessment.",
  serviceImpact: "Impact",
  serviceAction: "Action",

  // Common
  account: "Account",
  region: "Region",
  scanTime: "Scan Time",
  duration: "Duration",
  severityDistribution: "Severity Distribution",
  findingsByModule: "Findings by Module",
  details: "Details",

  // Extended \u2014 HTML Security Report extras
  topHighestRiskFindings: (n: number) =>
    `Top ${n} Highest Risk Findings`,
  resource: "Resource",
  impact: "Impact",
  riskScore: "Risk Score",
  showRemainingFindings: (n: number) =>
    `Show remaining ${n} findings\u2026`,
  trendTitle: "30-Day Trends",
  findingsBySeverity: "Findings by Severity",
  showMoreCount: (n: number) =>
    `Show ${n} more\u2026`,

  // Filter toolbar
  filterSeverity: "Severity:",
  filterModule: "Module:",
  filterAll: "All",
  filterAllModules: "All Modules",
  filterCountTpl: "Showing {shown} / {total} findings",

  // Extended \u2014 MLPS extras
  // Markdown report
  executiveSummary: "Executive Summary",
  totalFindingsLabel: "Total Findings",
  description: "Description",
  priority: "Priority",
  noFindingsForSeverity: (severity: string) => `No ${severity.toLowerCase()} findings.`,

  preCheckOverview: "Pre-Check Overview",
  accountInfo: "Account Information",
  checkedCount: (total: number, clean: number, issues: number) =>
    `Checked: ${total} items (No issues: ${clean} | Issues found: ${issues})`,
  uncheckedCount: (n: number) =>
    `Not checked: ${n} items (corresponding scan modules not run)`,
  cloudProviderCount: (n: number) =>
    `Cloud provider responsible: ${n} items`,
  manualReviewCount: (n: number) =>
    `Manual review required: ${n} items`,
  naCount: (n: number) => `Not applicable: ${n} items`,
  naNote: (n: number) =>
    `Not applicable: ${n} items (IoT/wireless networks/mobile terminals/ICS/trusted verification, etc.)`,
  unknownNote: (n: number) =>
    `(${n} items not checked \u2014 corresponding scan modules not run)`,
  cloudItemsNote: (n: number) =>
    `The following ${n} items are the responsibility of the AWS cloud platform and are outside the scope of this report per the shared responsibility model.`,
  mlpsFooterGenerated: (version: string) =>
    `Generated by AWS Security MCP Server v${version}`,
  mlpsFooterDisclaimer:
    "This report is for evidence collection reference and does not include compliance determination. A complete MLPS assessment must be conducted by a certified assessment institution.",
  andMore: (n: number) => `\u2026 and ${n} more`,
  remediationByPriority: "Remediation Items (by Priority)",
  affectedResources: (n: number) => `${n} resource${n === 1 ? "" : "s"} affected`,
  installWindowsPatches: (n: number, kbs: string) => `Install ${n} Windows patch${n === 1 ? "" : "es"} (${kbs})`,
  mlpsCategorySection: {
    "\u5b89\u5168\u7269\u7406\u73af\u5883": "I. Physical Environment Security",
    "\u5b89\u5168\u901a\u4fe1\u7f51\u7edc": "II. Communication Network Security",
    "\u5b89\u5168\u533a\u57df\u8fb9\u754c": "III. Area Boundary Security",
    "\u5b89\u5168\u8ba1\u7b97\u73af\u5883": "IV. Computing Environment Security",
    "\u5b89\u5168\u7ba1\u7406\u4e2d\u5fc3": "V. Security Management Center",
  },

  // Module display names
  moduleNames: {
    service_detection: "Security Service Detection",
    secret_exposure: "Secret Exposure",
    ssl_certificate: "SSL Certificate",
    dns_dangling: "Dangling DNS",
    network_reachability: "Network Reachability",
    iam_privilege_escalation: "IAM Privilege Escalation",
    public_access_verify: "Public Access Verification",
    tag_compliance: "Tag Compliance",
    idle_resources: "Idle Resources",
    disaster_recovery: "Disaster Recovery",
    security_hub_findings: "Security Hub",
    guardduty_findings: "GuardDuty",
    inspector_findings: "Inspector",
    trusted_advisor_findings: "Trusted Advisor",
    config_rules_findings: "Config Rules",
    access_analyzer_findings: "Access Analyzer",
    patch_compliance_findings: "Patch Compliance",
    imdsv2_enforcement: "IMDSv2 Enforcement",
    waf_coverage: "WAF Coverage",
    // Security Hub sub-categories
    "sh:FSBP": "Security Best Practices",
    "sh:Inspector": "Software Vulnerabilities",
    "sh:GuardDuty": "Threat Detection",
    "sh:Config": "Configuration Compliance",
    "sh:Access Analyzer": "External Access",
    "sh:Other": "Other Security Findings",
  },

  // Security Hub sub-categories
  securityHubSubCategories: {
    FSBP: { label: "Security Best Practices" },
    Inspector: { label: "Software Vulnerabilities" },
    GuardDuty: { label: "Threat Detection" },
    Config: { label: "Configuration Compliance" },
    "Access Analyzer": { label: "External Access" },
    Other: { label: "Other Security Findings" },
  },

  // Service Recommendations
  notEnabled: "Not Enabled",
  serviceRecommendations: {
    security_hub_findings: {
      icon: "\ud83d\udd34",
      service: "Security Hub",
      impact:
        "Cannot obtain 300+ automated security checks (FSBP/CIS/PCI DSS standards)",
      action:
        "Enable Security Hub for the most comprehensive security posture assessment",
    },
    guardduty_findings: {
      icon: "\ud83d\udd34",
      service: "GuardDuty",
      impact:
        "Cannot detect threat activity (malicious IPs, anomalous API calls, crypto mining, etc.)",
      action:
        "Enable GuardDuty for continuous threat detection",
    },
    inspector_findings: {
      icon: "\ud83d\udfe1",
      service: "Inspector",
      impact:
        "Cannot scan EC2/Lambda/container software vulnerabilities (CVEs)",
      action:
        "Enable Inspector to discover known security vulnerabilities",
    },
    trusted_advisor_findings: {
      icon: "\ud83d\udfe1",
      service: "Trusted Advisor",
      impact:
        "Cannot obtain AWS best practice security checks",
      action:
        "Upgrade to Business/Enterprise Support plan to use Trusted Advisor security checks",
    },
    config_rules_findings: {
      icon: "\ud83d\udfe1",
      service: "AWS Config",
      impact:
        "Cannot check resource configuration compliance status",
      action:
        "Enable AWS Config and configure Config Rules",
    },
    access_analyzer_findings: {
      icon: "\ud83d\udfe1",
      service: "IAM Access Analyzer",
      impact:
        "Cannot detect whether resources are accessed by external accounts or public networks",
      action:
        "Create IAM Access Analyzer (account-level or organization-level)",
    },
    patch_compliance_findings: {
      icon: "\ud83d\udfe1",
      service: "SSM Patch Manager",
      impact:
        "Cannot check instance patch compliance status",
      action:
        "Install SSM Agent and configure Patch Manager",
    },
  },

  // HW Defense HTML Report
  hwReportTitle: "HW Defense Security Assessment Report",
  hwAutoCheck: "Automated Checks",
  hwManualCheck: "Manual Verification Items",
  hwNoAutoCheck: "No automated checks for this section",
  hwClean: "No issues found",
  hwTotalFindings: "Total Findings",
  hwSectionsChecked: "Sections Checked",
  hwAutoVerified: "Auto-Verified",
  hwManualPending: "Manual Pending",
  hwManualCount: (n: number) => `${n} manual item${n === 1 ? "" : "s"}`,
  hwReportDisclaimer: "This report is organized by HW Defense SOP checklist categories, for reference only.",
  hwSectionNames: {
    attack_surface: { name: "Attack Surface Reduction", icon: "🎯" },
    vulnerability_patch: { name: "Vulnerability & Patch Management", icon: "🩹" },
    identity_credential: { name: "Identity & Credential Security", icon: "🔑" },
    transport_security: { name: "Transport & Instance Security", icon: "🔒" },
    security_services: { name: "Security Service Status", icon: "🛡️" },
    emergency_response: { name: "Emergency Response Readiness", icon: "🚨" },
    environment_control: { name: "Environment Control", icon: "🏗️" },
    post_review: { name: "Post-Drill Optimization", icon: "📊" },
  },
  hwManualItems: {
    attack_surface: ["Draw ingress/egress path architecture diagram, mark all Internet/DX dedicated line paths"],
    vulnerability_patch: ["Contact security vendors for simulated attack drills (penetration testing)", "Monitor AWS security advisories (known vulnerabilities and patches)"],
    identity_credential: ["All IAM users must have MFA enabled", "Access key rotation cycle ≤ 90 days", "Avoid shared account usage", "No plaintext passwords in S3/Lambda/application code"],
    transport_security: ["Verify all external-facing services use TLS 1.2+", "Check internal service-to-service communication encryption"],
    security_services: ["Verify Security Hub is enabled with standards configured", "Verify GuardDuty is enabled in all regions", "Verify CloudTrail multi-region logging is enabled", "Verify Config Rules are configured"],
    emergency_response: ["Prepare dedicated isolation security groups (no Inbound/Outbound rules)", "Establish instance isolation SOP: Alert → Investigate → Block attacker IP → Network isolation → Security response → Log attack details", "Form 7×24 monitoring rapid response team", "Create dedicated communication channels for the drill period (Teams/Slack/Chime)", "Establish WAR-ROOM connection with AWS TAM (Enterprise Support customers)"],
    environment_control: ["Shut down non-critical systems during the drill period", "Shut down test/dev environments or maintain same security baseline as production", "Confirm which environments can be emergency-stopped to prevent attack propagation"],
    post_review: ["Address and remediate each item from the attack report", "Establish periodic security maintenance processes with the security team", "Continuously fill security risk gaps"],
  },

  // HW Checklist (full composite)
  hwChecklist: `
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550
\ud83d\udccb Cyber Defense Drill Supplementary Reminders (Beyond Automated Scanning)
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550

The following items require manual verification and execution:

\u26a0\ufe0f Emergency Isolation / Incident Response Plan
  \u25a1 Prepare dedicated isolation security groups (no Inbound/Outbound rules)
  \u25a1 Establish instance isolation SOP: Alert \u2192 Investigate \u2192 Block attacker IP \u2192 Network isolation \u2192 Security response \u2192 Log attack details
  \u25a1 Define emergency response procedures for each system (production core/non-core/test/dev)
  \u25a1 Identify responsible personnel and contacts for each project account and resource

\u26a0\ufe0f Test/Development Environment Handling
  \u25a1 Shut down non-critical systems during the drill period
  \u25a1 Shut down test/dev environments or maintain same security baseline as production
  \u25a1 Confirm which environments can be emergency-stopped to prevent attack propagation

\u26a0\ufe0f On-Duty Team Formation
  \u25a1 7\u00d724 monitoring and rapid response team
  \u25a1 Technical and risk analysis team
  \u25a1 Security policy deployment team
  \u25a1 Business response team
  \u25a1 Confirm AWS TAM/Support contact information (ES/EOP customers)

\u26a0\ufe0f Ingress/Egress Path Architecture Diagram
  \u25a1 Ensure all Internet/DX dedicated line ingress/egress paths are clearly marked in architecture diagrams
  \u25a1 Clarify data flow for each ELB/Public EC2/S3/DX
  \u25a1 Identify all internet-facing data interaction interfaces

\u26a0\ufe0f Proactive Penetration Testing
  \u25a1 Contact security vendors for simulated attack drills before the exercise
  \u25a1 Conduct security hardening based on penetration test reports
  \u25a1 Monitor AWS security advisories (known vulnerabilities and patches)

\u26a0\ufe0f WAR-ROOM Real-Time Communication
  \u25a1 Create dedicated communication channels for the drill period (Teams/Slack/Chime)
  \u25a1 Establish WAR-ROOM connection with AWS TAM (Enterprise Support customers)
  \u25a1 Standardize case title format: "[CyberDrill] + Issue Description"

\u26a0\ufe0f Password & Credential Management
  \u25a1 All IAM users must have MFA enabled
  \u25a1 Access key rotation cycle \u2264 90 days
  \u25a1 Avoid shared account usage
  \u25a1 No plaintext passwords in S3/Lambda/application code

\u26a0\ufe0f Post-Drill Optimization
  \u25a1 Address and remediate each item from the attack report
  \u25a1 Establish periodic security maintenance processes with the security team
  \u25a1 Continuously fill security risk gaps

Reference: AWS Cyber Defense Drill Standard Operation Procedure (Compliance IEM)
`,
};
